### ISSUE TITLE
Add documentation on parent levels in preview

### ISSUE THREAD

**Issue by astauffer92** [infocentric/ic-fe-blueprint#7]
A documentation (Readme.md) can also be added directly below `/src` or below `/atom`, `/molecules` or `/organisms` or `/pages` or inside the `/doc` folder of each component. Those documentations should be displayed when the respective level is selected in the navigation in the preview.

**Comment by tho89** [comment]
Every hit to a route below `/:type/**` now returns either the contents of a README.md file, a `${view}.md` file, or a message that the documenation for this endpoint is missing.
