### ISSUE TITLE
Add search overview to all levels of navigation

### ISSUE THREAD

**Issue by astauffer92** [infocentric/ic-fe-blueprint#9]
Whenever user is navigating in the preview and is not on the level of a view, then he should see the search overview to search for the component.

**Comment by tho89** [comment]
![image](https://user-images.githubusercontent.com/1911324/53507712-a9486c00-3ab8-11e9-9be5-c1da9a503948.png)
@astauffer92 is there anything more needed?

**Comment by astauffer92** [comment]
Yes exactly this, but for each level of the navigation
eg.
/ -> display all views
/atoms -> display all atom views
/atoms/text -> display all atom-text views

Additional the search should be a "contain" search. When i tried it was a "startswith" search.
